# https://medium.com/@quen09t/automating-flutter-web-deployments-to-firebase-hosting-using-github-actions-4893e4f17135
name: Automatic Deployment

on: [push]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŽ¯ Deploy to firebase
      - uses: actions/checkout@v3
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACELY_F42F5 }}"
          channelId: live
          projectId: tracely-f42f5